filebeat.inputs:
  - type: log
    paths:
      - /var/logs/voter/voter.log
    fields:
      app_name: "voter"
    json.keys_under_root: true     
    json.add_error_key: true

  - type: log
    paths:
      - /var/logs/voter2/voter2.log
    fields:
      app_name: "voter2"
    json.keys_under_root: true     
    json.add_error_key: true

output.logstash:
  hosts: ["logstash:5044"]