version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASS}
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${ELASTIC_PORT}:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    ports:
      - "${KIBANA_PORT}:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=true
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASS}
      - xpack.encryptedSavedObjects.encryptionKey=my_super_secret_key_1234567890abcdef
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    env_file: .env
    container_name: logstash
    volumes:
      - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/pipeline/logstash.conf
    networks:
      - elk
    ports:
      - "${LOGSTASH_PORT}:5044"
    environment:
      - ELASTIC_USER=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASS}
      - ELASTIC_HOSTS=http://elasticsearch:9200
      - "LS_JAVA_OPTS: -Xmx2g -Xms512m"
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:${STACK_VERSION}
    env_file: .env
    container_name: filebeat
    command: filebeat -e -strict.perms=false -c /usr/share/filebeat/filebeat.yml
    environment:
      - ELASTIC_USER=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASS}
      - ELASTIC_HOSTS=http://elasticsearch:9200
      - KIBANA_HOSTS=http://kibana:5601
      - LOSTASH_HOSTS=http://logstash:5044
    volumes:
      - ${FILEBEAT_PATH}:/usr/share/filebeat/filebeat.yml
      - app1-logs:/var/logs/${APP1_NAME}
      - app2-logs:/var/logs/${APP3_NAME}
      - ${PATH_TO_LOGS_HARD_FIRST}:/var/logs/${APP2_NAME}
    depends_on:
      - logstash
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elastic_data:
    driver: local
  app1-logs:
    name: ${APP1_VOLUME_NAME}
  app2-logs:
    name: ${APP2_VOLUME_NAME}
